fix some bugs

diff --git a/secconf/check/check_secure_boot b/secconf/check/check_secure_boot
--- a/secconf/check/check_secure_boot
+++ b/secconf/check/check_secure_boot
@@ -5,15 +5,15 @@ secure_boot_comm()
         get_usr_input "The current system doesn't support secure boot!"
         return 1
     fi
-    get_usr_input "Pesign is about to be installed?【Y/N】"
+    check_rpm_package pesign
     if [ $? -eq 1 ]; then
-        yum install -y pesign || exit 1
+        return 1
     fi
-    get_usr_input "Mokutil is about to be installed?【Y/N】"
+    check_rpm_package mokutil
     if [ $? -eq 1 ]; then
-        yum install -y mokutil || exit 1
+        return 1
     fi
-    if [ ! -f /boot/efi/EFI/secure_boot.der ]; then
+    if [ ! -s /boot/efi/EFI/secure_boot.der ]; then
         get_usr_input "Secure Boot certificate of openeuler is about to be downloaded?【Y/N】"
         if [ $? -eq 1 ]; then
             wget -O /boot/efi/EFI/secure_boot.der https://www.openeuler.org/certificates/openEuler-x509ca.cer.der --no-check-certificate &> /dev/null
@@ -34,6 +34,32 @@ secure_boot_comm()
             return 1
         fi
     done
+    if [ -s /boot/vmlinuz-"$(uname -r)" ]; then
+        check_rpm_package gzip
+        if [ $? -eq 1 ]; then
+            return 1
+        fi
+        if [ $(arch) == "aarch64" ]; then
+            cp -ar /boot/vmlinuz-"$(uname -r)" ./vmlinuz-"$(uname -r)".gz
+            gzip -df vmlinuz-"$(uname -r)".gz
+            if [ $? -ne 0 ]; then
+                echo "failed to gzip vmlinuz, stop check"
+                rm -f vmlinuz-"$(uname -r)".gz
+                return 1
+            fi
+        else
+            cp -ar /boot/vmlinuz-"$(uname -r)" ./vmlinuz-"$(uname -r)"
+        fi
+        pesigcheck -i vmlinuz-"$(uname -r)" -n 0 -c /boot/efi/EFI/secure_boot.der
+        if [ $? -ne 0 ]; then
+            echo "$vmlinuz-"$(uname -r)" signature verification failed!"
+        else
+            echo "The kernel of the current version has been verified"
+        fi
+        rm -f vmlinuz-"$(uname -r)"
+    else
+        echo "The vmlinuz was not found, please check the signature manually"
+    fi
 
     mokutil --db | grep "Issuer: CN=CA, OU=Infra, O=openEuler, L=ShenZhen, ST=GuangDong, C=CN"
     if [ $? -ne 0 ]; then
